### ISSUE TITLE
Fix account creation with login.fanfares.io

### ISSUE THREAD

**Issue by arkin0x** [fanfares/fanfares#66]
It would be nice to get this working before Prague, but if not, maybe we just use nsec.app?

**Comment by rleed** [comment]
There appears to be a disconnect between nostr-login and noauthd such that the result of the RPC call create_account does not make it back to the caller (nostr-login). Instead, nostr-login reports an error (randomly either "Bad domain" or "Not authorized"). Nevertheless, noauthd is doing its job, and if the user ignores the error and assumes success, it is possible to create a new account and login. (Note that notification permissions must be enabled on the third app, login.fanfares.io, otherwise it will display "Denied" and fail to create the account.)

**Comment by arkin0x** [comment]
Putting on hold until Artur fixes it. He acknowledged the issue and said it happens for others too.
